Resources:
  WsUserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: WsUserTable
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
        - AttributeName: watchedGame
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: watchedGame-index
          KeySchema:
          - AttributeName: watchedGame
            KeyType: HASH
          Projection: 
            ProjectionType: "ALL"
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  UserInfoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UserInfo
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
  GameTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Game
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST