Resources:
  WsUserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: WsUserTable
      AttributeDefinitions:
        - AttributeName: ConnectionId
          AttributeType: S
      KeySchema:
        - AttributeName: ConnectionId
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST